spring.application.name=pahadi-punjabi-yatra
spring.datasource.url=jdbc:postgresql://localhost:5432/pahadipunjabiyatra
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true